import { Inter } from 'next/font/google'
import './globals.css'
import Homebanner from '@/components/home/banner/Homebanner';
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-full'>
        <Homebanner />
        {children}
        <Footer />
      </body>
    </html>
  )
}
